title: Ming Chong Lim
nav:
  - title: Education
    url: /education.html
  - title: Work Experience
    url: /experience.html
  - title: Awards and Competitions
    url: /awards.html
  - title: Projects
    url: /projects.html
  - title: Skills
    url: /skills.html
  - title: Gallery
    url: /gallery.html
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
