title: mc.dev
description: Welcome to my personal website, feel free to look around!
nav: # refer to https://jekyllrb.com/tutorials/navigation/
  - title: Education
    url: /education.html
  - title: Work Experience
    url: /experience.html
  - title: Awards and Competitions
    url: /awards.html
  - title: Projects
    url: /projects.html
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
